version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: horus-postgres
    environment:
      POSTGRES_USER: horus
      POSTGRES_PASSWORD: horus
      POSTGRES_DB: horus
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elastic:/usr/share/elasticsearch/data

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.5.3
    environment:
      - CONFIG_SUPPORT_ESCAPE=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - postgres
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/postgresql-42.2.18.jar:/usr/share/logstash/postgresql-42.2.18.jar
    ports:
      - "5000:5000"