version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: horus-postgres
    environment:
      POSTGRES_USER: horus
      POSTGRES_PASSWORD: horus
      POSTGRES_DB: horus
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./logstash-pipeline/:/usr/share/logstash/pipeline/
    ports:
      - "5044:5044" # Beats input port
      - "9600:9600" # Logstash monitoring API
    environment:
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
    networks:
      - log_network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - "9200:9200"
    networks:
      - log_network


  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - log_network
    depends_on:
      - elasticsearch

volumes:
  postgres:
  logstash:


networks:
  log_network:
    driver: bridge
